# nom du workflow
name: Premier workflow
# événement déclencheur du workflow
on: 
  - workflow_dispatch
  - push
# liste des jobs à exécuter
jobs:
  premier_job:
    runs-on: ubuntu-latest
# liste des étapes à exécuter dans le job
    steps:
      - name: Dit bonjour
        run: echo "Hello world"
      - name: Dit au revoir
        run: echo "Goodbye world"
# Deuxième job
  deuxieme_job:
    runs-on: ubuntu-latest
    steps:
      - name: etape 2
        run: echo "This is the second job"

  